### ISSUE TITLE
python3 woes

### ISSUE THREAD

**Issue by SimonEnsemble** [tobacco-mofs/tobacco_3.0#14] opened 2020-10-14 21:42 UTC
hi! FYI `python3 tobacco.py` gives:

```
=========================================================================================================
template : pcu.cif
=========================================================================================================

Traceback (most recent call last):
  File "tobacco.py", line 420, in <module>
    run_tobacco_serial(templates, CHARGES)
  File "tobacco.py", line 396, in run_tobacco_serial
    run_template(template)
  File "tobacco.py", line 86, in run_template
    for net in ct2g(template):
  File "/home/cokes/scratch/tobacco_3.0/ciftemplate2graph.py", line 158, in ct2g
    v1 = G.node[s[0]]['fcoords']
AttributeError: 'MultiGraph' object has no attribute 'node'

```

but runs successfully with `python2 tobacco.py`

**Comment by rytheranderson** [comment] 2020-10-14 22:11
Hello,

I think this is caused by using networkx 2.4+ for which node attributes are referenced by G.nodes rather than G.node for any type of networkx graph. Currently, the conda install recommendations for ToBaCCo will install networkx 2.2 by default, for which both types of node attribute references work. That being said, the G.node is deprecated in 2.2 and obsolete in 2.4+, so I fixed all the old G.node references. I just tested with both networkx 2.2 and 2.5 and everything seems to work fine. Please let me know if this solved the problem for your Python environment and I will close the issue. I will also update the readme with package versions.

**Comment by SimonEnsemble** [comment] 2020-10-14 23:17
hi Ryan, thanks!
I indeed was on networkx v2.4 in python 3.
I use `pip` instead of conda, so just ran `tobacco.py` in the cloned github repo, explaining why I didn't inherit the right version of networkx.

I `git pull`d just now, and `python3 tobacco.py` works :partying_face:

**Closed as completed** 2020-10-14 23:17 UTC
